# *This is Python Tutorial*

In [2]:
import numpy as np

In [43]:
a = np.array([[1, 2, 3, 4, 5], [1, 6, 3, 4, 9]])
b = np.array([1, 6, 3, 4, 9])

#Ways to select an element from Numpy Array
print(a[1][2], a[1,3])

#Shows the dimensions of an array
print(a.ndim, b.ndim)

#Shows how many elements are in an specific array
a.shape[0]

#Total elements in the array
a.size


3 4
2 1


10

In [63]:
#Creates an array with range
''' = np.array([np.arange(0, 10, 2), np.arange(10, 20, 2)]) 
print(c)
print(c.ndim)'''

# The function "range" doesn`t create a list

# Randomize an array
'''d = np.random.permutation(np.arange(10))
print(d)'''

# Creates an array with int numbers
e = np.random.randint(20,30)
print(e)

# This function reshape an array as a matrix
D = np.arange(100).reshape(4,25)
D


24


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
a1 = np.arange(100)
b1 = a1[:].copy() #Create a independent copy on numpy
b1

array([3, 4, 5, 6, 7, 8, 9])

In [76]:
V = np.round(10*np.random.rand(5,4))

#Slicing in deferent ways
print(V)
print(V[1,:], V[:,1])
print(V[1:3,2:4])

[[0. 8. 1. 5.]
 [3. 7. 7. 1.]
 [3. 4. 8. 3.]
 [6. 5. 6. 1.]
 [4. 1. 5. 8.]]
[3. 7. 7. 1.] [8. 7. 4. 5. 1.]
[[7. 1.]
 [8. 3.]]
